[package]
name        = "coral-blas"
version     = "0.1.0"
edition     = "2024"
authors     = ["deval deliwala <devaldeliwala@berkeley.edu>"]

license     = "MIT"
description = "a pure-rust blas implementation for aarch64."
readme      = "README.md"
repository  = "https://github.com/devdeliw/CORAL"

categories  = ["science", "mathematics", "algorithms"]
keywords    = ["linear-algebra", "algebra", "matrix", "vector", "math"] 

exclude = [
  "benches/**",
  "*.png",
]

[lib]
name = "coral"             
path = "src/lib.rs"

[dependencies]
blas-src = { version = "0.12", optional = true, default-features = false }

# for comparison benchmarks 
[features]
default    = []
accelerate = ["blas-src/accelerate"]
openblas   = ["blas-src/openblas"]

[dev-dependencies]
criterion = "0.5"   
cblas-sys = "0.1" 

[package.metadata.docs.rs]
features = ["default"]
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

## level 1 
[[bench]] 
name    = "level1_asum"
harness = false 
[[bench]] 
name    = "level1_axpy" 
harness = false
[[bench]] 
name    = "level1_scal" 
harness = false 
[[bench]] 
name    = "level1_swap" 
harness = false 
[[bench]] 
name    = "level1_copy" 
harness = false
[[bench]] 
name    = "level1_nrm2" 
harness = false
[[bench]] 
name    = "level1_iamax"
harness = false
[[bench]] 
name    = "level1_dot" 
harness = false 

## level 2 
[[bench]] 
name    = "level2_gemv" 
harness = false 
[[bench]] 
name    = "level2_trmv" 
harness = false
[[bench]] 
name    = "level2_trsv" 
harness = false 
[[bench]]
name    = "level2_symv"
harness = false 
[[bench]]
name    = "level2_hemv"
harness = false

## level 3 
# single precision 
[[bench]] 
name    = "level3_sgemm_nn" 
harness = false 
[[bench]] 
name    = "level3_sgemm_tt" 
harness = false 

# double precision 
[[bench]] 
name    = "level3_dgemm_nn" 
harness = false 
[[bench]] 
name    = "level3_dgemm_tt" 
harness = false 

# complex single precision 
[[bench]] 
name    = "level3_cgemm_nn" 
harness = false 
[[bench]] 
name    = "level3_cgemm_tt" 
harness = false 
[[bench]] 
name    = "level3_cgemm_cc" 
harness = false

# complex double precision
[[bench]] 
name    = "level3_zgemm_nn" 
harness = false 
[[bench]] 
name    = "level3_zgemm_tt" 
harness = false
[[bench]] 
name    = "level3_zgemm_cc" 
harness = false 
