[package]
name    = "coral"
version = "0.1.0"
edition = "2024"

[dependencies]
cblas-sys   = "0.1"

[dev-dependencies]
criterion = "0.5"

[[bench]] 
name    = "level2_sgemv" 
harness = false 
[[bench]] 
name    = "level2_strmv" 
harness = false
[[bench]] 
name    = "level2_strsv" 
harness = false 
[[bench]]
name    = "level2_sger" 
harness = false
